### PR TITLE
Added Lotería (Spanish Lottery)

### PR DESCRIPTION
**Pull request by tvermaashutosh**
Submitting this PR means you have:

- [x] searched the [readme](https://github.com/edm00se/awesome-board-games/edit/main/readme.md) file and searched the [open pull requests](https://github.com/edm00se/awesome-board-games/pulls) (no duplicates please)
- [x] and will follow [the desired format](https://github.com/edm00se/awesome-board-games/blob/main/formatting.md)
- [x] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines](https://github.com/edm00se/awesome-board-games/blob/main/contributing.md) or [open an issue](https://github.com/edm00se/awesome-board-games/issues/new).

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

### CODE REVIEW

**Comment by tvermaashutosh** [comment]
@edm00se 
Kindly tell me how to resolve this issue. I don't know what the problem is from my side. Could you please resolve this and merge it.

**Comment by edm00se** [comment]
The linter is complaining about a dead url, which does not appear to be accurate. The preview build by vercel failed to run because with the higher volume of people contributing this month, we’ve exceeded my free account’s build limit. I believe that should be cleared within 24 hours. As for the lint action, a re-run didn’t fix it, so I’ll have a look later this evening. Thanks.

**Comment by tvermaashutosh** [comment]
@edm00se 
Ok Eric, I understand.
Thanks for your reply. Look into it and see if it fixes the issue.

**Comment by edm00se** [comment]
I'm looking into the linter, which is giving us the false positive on the dead url check.

**Comment by tvermaashutosh** [comment]
Ok @edm00se lemme do these changes and make new commits

**Comment by tvermaashutosh** [comment]
@edm00se 
Thank you for your valuable assistance.
All my checks have passed when I updated the link.
I request you to kindly review my PR and merge it.

**Review by edm00se — APPROVED** [review]
Things are looking good! Thank you for contributing.

refs #269

**Pull request merged**
