### PR TITLE
Added The Crew: The Quest for Planet Nine board games

### PR DESCRIPTION
**Pull request by SusheelThapa**
Submitting this PR means you have:

- [X] searched the [readme][readme-url] file and searched the [open pull requests][pr-url] (no duplicates please)
- [X] and will follow [the desired format][format-url]
- [X] used image links that resolve correctly, are appropriately sized, and are served over HTTPS

Once your PR is created, it will trigger a build a GitHub Action (Awesome-Lint). This includes a format linting process, so if there are any issues with the build, please address them.

Do you have further questions? Check the [contribution guidelines][contributing-url] or [open an issue][new-issue-url].

When you're ready, check off the above acknowledgements and continue with your Pull Request... and thanks!

[pr-url]: https://github.com/edm00se/awesome-board-games/pulls
[readme-url]: https://github.com/edm00se/awesome-board-games/edit/main/readme.md
[format-url]: https://github.com/edm00se/awesome-board-games/blob/main/formatting.md
[contributing-url]: https://github.com/edm00se/awesome-board-games/blob/main/contributing.md
[new-issue-url]: https://github.com/edm00se/awesome-board-games/issues/new

### CODE REVIEW

**Comment by edm00se** [comment]
@SusheelThapa please stop creating new PRs until all existing ones have been dealt with. I recommend you limit yourself in the volume you create in a single repository. Also please read the freshly [updated section of the welcome issue, titled “Notts for First Time Contributors”](https://github.com/edm00se/awesome-board-games/issues/269), as you are new this year.

**Comment by SusheelThapa** [comment]
@edm00se I am sorry. From next time onward, I will create new PRs after my all existing one have been dealt with. I am extremely sorry toward the inconvenience that i have created.

**Comment by edm00se** [comment]
Thank you. I'll get caught up eventually.

**Review by edm00se — APPROVED** [review]
refs #269

**Pull request merged**
