### PR TITLE
Reorder board games using alphabetical order

### PR DESCRIPTION
**Pull request by LucasBassetti**

### CODE REVIEW

**Comment by edm00se** [comment]
I've avoided doing this to-date as it's bound to be a headache to maintain manually. Doing it in an automated fashion would be great, but relies on a formatter running. I had one via a GitHub Action, but it stopped working correctly today and I'm going to revisit that thought later on.

Until that point, I'm going to wait on implementing this. It may make the readme a bit "messy" for now, but it's functional. Alphabetization is great if you know what you're looking for already, in which case the search functionality of either `CTRL + F` or the search component in the generated version of the "live site" should fulfill this need.

**Comment by edm00se** [comment]
🤔 This _would_ eliminate confusion over where to insert, and by proxy reduce 🤞 merge conflicts, as this grows. I may need to look into automating this further in the near future.

**Comment by LucasBassetti** [comment]
One manual way for PRs is create a [PR template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) with a check mark for remember contributors to put in alphabetical order.

**Comment by edm00se** [comment]
Thank you again for taking the time to open this PR. As I described in [my reply on PR #89](https://github.com/edm00se/awesome-board-games/pull/89#issuecomment-539021176), the way I see this being resolved is through automation. If you want help work towards that goal, you are welcome to do so. Let me know if you'd like any of the cards from [the project board](https://github.com/edm00se/awesome-board-games/projects/2) converted to an issue and assigned to you.

**Pull request closed without merging**
